/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_external_cameraService_helper_SensorJniHelper */

#ifndef _Included_com_external_cameraService_helper_SensorJniHelper
#define _Included_com_external_cameraService_helper_SensorJniHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_external_cameraService_helper_SensorJniHelper
 * Method:    sendSensorEventRemote
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_external_cameraService_helper_SensorJniHelper_sendSensorEventRemote
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_external_cameraService_helper_SensorJniHelper
 * Method:    sendSensorDataRemote
 * Signature: (I[FII)I
 */
JNIEXPORT jint JNICALL Java_com_external_cameraService_helper_SensorJniHelper_sendSensorDataRemote
  (JNIEnv *, jobject, jint, jfloatArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
